---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Installing Necessary Packages
```{r Loading packages}
install.packages("faraway")
install.packages("leaps")
install.packages("Amelia")
install.packages("pls")
```

##Loading Necessary Packages into environment
```{r Loading in necessary packages}
#install.packages("MASS")
library(MASS)
#install.packages("faraway")
library(faraway)
#install.packages("nlme")
library(nlme)
library(leaps)
library(Amelia)
library(pls)
```

##Loading raw data
```{r Loading raw data}

#Loading data
data_raw <- read.csv("data_nomiss_specificAQI_updatedNov25.csv")
#Dropping missing values in response
data_raw <- data_raw[!is.na(data_raw$AQI),]
#Assigning date from year, month, day
data_raw$date <- as.numeric( difftime(ISOdate(data_raw$Year, data_raw$Month, data_raw$Day, 0), ISOdate(2016,1,1,0), units="days"))

```

##Data Cleaning
```{r Data Cleaning}
#TEMPERATURE DATA
  plot(data_raw$Temperature, data_raw$Month)
  data_raw[data_raw$Temperature < -30,]
  
  # remove iberville, louisiana since it is unlikely a county in LA actually saw 
  #temperatures in the -38 range
    remove <- c("iberville")
    data1 <- data_raw
    data1 <- data1[!(data1$County %in% remove),]
  
  plot(data1$Temperature, data1$Month)
  data1[which(data1$Temperature < -15 & data1$Temperature > -20 & data1$Month == 4),]
  
  
  # remove effingham, illinois, greenup, kentucky, and roane, tennessee since 
  #they have the exact same value for every day and is unlikely to have -17.78 
  #in the middle of the summer
    remove2 <- c("effingham", "greenup")
    data2 <- data1[!(data1$County %in% remove2),]
  
    data2[which(data2$Temperature < -15 & data2$Temperature > -20 & data2$Month == 7),]
    
    remove3 <- c("roane")
    data3 <- data2[!(data2$County %in% remove3),]
    
  plot(data3$Temperature, data3$Month)
  
  qqnorm(data3$Temperature)
  qqline(data3$Temperature)
  #probably needs transformation


#AQI_PM2.5
  summary(data_raw$AQI_PM2.5)
  plot(data_raw$AQI_PM2.5)
  #all values within 0-500 range
  
  qqnorm(data_raw$AQI_PM2.5)
  qqline(data_raw$AQI_PM2.5)
  #probably needs transformation
  
  
#AQI_PM10
  summary(data_raw$AQI_PM10)
  plot(data_raw$AQI_PM10, data_raw$Month)
  #not all values within 0-500 range
  
  #remove values which are outside of the AQI range of 0-500 since 
  #something is not right with those values
    data_raw[which(data_raw$AQI_PM10 > 500),]
    remove4 <- c(8912, 13425)
    data4 <- data3[-remove4,]
    data4[which(data4$AQI_PM10 > 500),]

  plot(data4$AQI_PM10, data4$Month)
    
  qqnorm(data4$AQI_PM10)
  qqline(data4$AQI_PM10)
  #probably needs transformation

  
#AQI_CO
  summary(data_raw$AQI_CO)
  plot(data_raw$AQI_CO, data_raw$Month)
  #all values within 0-500 range
  
  qqnorm(data_raw$AQI_CO)
  qqline(data_raw$AQI_CO)
  #probably needs transformation
  
  
#AQI_NO2
  summary(data_raw$AQI_NO2)
  plot(data_raw$AQI_NO2, data_raw$Month)
  #all values within 0-500 range
  
  qqnorm(data_raw$AQI_NO2)
  qqline(data_raw$AQI_NO2)
  #probably needs transformation
  
#AQI_Ozone
  summary(data_raw$AQI_Ozone)
  plot(data_raw$AQI_Ozone, data_raw$Month)
  #all values within 0-500 range
  
  qqnorm(data_raw$AQI_Ozone)
  qqline(data_raw$AQI_Ozone)
  #probably needs transformation
  
#AQI_SO2
  summary(data_raw$AQI_SO2)
  plot(data_raw$AQI_SO2, data_raw$Month)
  #all values within 0-500 range
  
  qqnorm(data_raw$AQI_SO2)
  qqline(data_raw$AQI_SO2)
  
  qqnorm(data4$AQI_SO2)
  qqline(data4$AQI_SO2)
  
  data4[which(data4$AQI_SO2 == 200),]
  #remove hawaii, hawaii since every single recorded day has the same AQI_SO2
    remove5 <- c("hawaii")
    data5 <- data4[!(data4$County %in% remove5),]
  
  qqnorm(data5$AQI_SO2)
  qqline(data5$AQI_SO2)
  #probably needs transformation
  

#TOTAL EMISSIONS
  summary(data_raw$Total.Emissions)
  plot(data_raw$Total.Emissions, data_raw$Month)
  
  data_raw[which(data_raw$Total.Emissions == max(data_raw$Total.Emissions)),]
  
  #harris county (county which houses Houston) has much more total emissions 
  #than the others, but no real reason to believe it's a bad data point
  
  qqnorm(data5$Total.Emissions)
  qqline(data5$Total.Emissions)
  #probably needs transformation

  
#TESS FINAL DATA (NOT INCLUDING IAN'S REMOVALS)
data <- data5

```

##Running full model
```{r Full model}
lmod <- lm(formula = AQI ~ NF3 + Other.GHG + Total.Emissions + HFC + Other.Fluorane + Biogenic.CO2 + Population + CO2 + PFC + HFE + Stationary.Combustion + pp_consumed_MMBtu + Temperature +  Methane + SF6 + Short.Lived.Compounds + Income +  pp_net_gen_MWh, data = data)

summary(lmod)
```


##Check for and remove large leverage points
```{r Diagnostics}

#--------------------Constant Variance--------------------
#Plot residuals against fitted
plot(lmod$fitted.values, sqrt(abs(lmod$residuals)), xlab="Fitted", ylab=expression(sqrt(hat(epsilon))), main="Residuals vs. Fitted")
abline(h=0)


summary(lm(sqrt(abs(residuals(lmod))) ~ fitted(lmod)))
#--------------------Normality--------------------
#Checking normality with QQ-plot
qqnorm(lmod$residuals, ylab="Residuals", main="QQ Plot of Residuals")
qqline(residuals(lmod))

#Checking normality with histogram of residuals
hist(residuals(lmod), xlab="Residuals", main="Histogram of Residuals")

#Checking normality with Shapiro-Wilks test
shapiro.test(lmod$residuals[1:4999])

#--------------------Checking Leverage Points--------------------
#Obtaining leverages
hatv <- hatvalues(lmod)

#Comparing leverages to the halfnormal distribution
halfnorm(hatv, labs=data$County, ylab="Leverages")

#Removing large leverage points
data_mod <- data[hatv < 0.2,]


#--------------------Checking for Outliers--------------------
#Calculating Studentized Residuals
stud <- rstudent(lmod)

#Removing large influence points
data_mod <- data_mod[stud < 10,]


#--------------------Checking for Multicollinearity--------------------
#Calculating t(X) %*% X
x <- model.matrix(lmod)[,-1]

#Calculating VIFs for all variables
vif(x)

#Calculating correlation matrix over the variables
corr <- cor(data[,c("AQI", "HFC", "Other.GHG", "SF6", "Stationary.Combustion", "Biogenic.CO2", "HFE", "NF3", "PFC", "Short.Lived.Compounds", "Temperature", "pp_consumed_MMBtu", "CO2", "Income", "Nitrous.Oxide", "Population", "Total.Emissions", "pp_net_gen_MWh", "Methane", "Other.Fluorane")])

```

The following variables exhibit significant correlations with other variables, and will be dropped:

Short.Lived.Compounds
CO2
Total.Emissions
pp_net_gen_MWh
Other.Fluorane

```{r Refitting model}

lmod.nocol <- lm(formula = AQI ~ NF3 + Other.GHG + HFC +  Biogenic.CO2 + Population + PFC + HFE + Stationary.Combustion + pp_consumed_MMBtu + Temperature + Methane + SF6 + Income, data = data_mod)

summary(lmod.nocol)
```

```{r Data Transformations}

#--------------------Fitting optimal box-cox transformation--------------------
#Making response AQI positive by adding a small constant (1) -- can change later
data_mod$AQI <- data_mod$AQI + 1

#Getting model Likelihoods on a range of parameters
bx <- boxcox(lmod.nocol, plotit=T, lambda=seq(0.0, 1.0, by=0.001))

#Getting best boxcox parameter -- lambda ~ 0.5
lambda <- bx$x[which.max(bx$y)]

#Transforming model accordingly
lmod.T <- lm(formula = AQI ^ lambda ~ NF3 + Other.GHG + HFC +  Biogenic.CO2 + Population + PFC + HFE + Stationary.Combustion + pp_consumed_MMBtu + Temperature + Methane + SF6 + Income, data = data_mod)

summary(lmod.T)

#--------------------Re-checking Normality--------------------
#Checking normality with QQ-plot
qqnorm(lmod.T$residuals, ylab="Residuals", main="QQ Plot of Residuals (Transformed)")
qqline(residuals(lmod.T))

#Checking normality with histogram of residuals
hist(residuals(lmod.T), xlab="Residuals", main="Histogram of Residuals (Transformed)")

#Checking normality with Shapiro-Wilks test
shapiro.test(lmod.T$residuals[1:4999])

```


```{r Weighted Least Squares}
#Calculating variance vector
var <- (2.4804564 + 0.0193670*lmod$fitted.values) ^ 2

lmod_wls <- lm(formula = AQI ~ NF3 + Other.GHG + Total.Emissions + HFC + Other.Fluorane + Biogenic.CO2 + Population + CO2 + PFC + HFE + Stationary.Combustion + pp_consumed_MMBtu + Temperature +  Methane + SF6 + Short.Lived.Compounds + Income +  pp_net_gen_MWh, data = data, weights=1/var)

summary(lmod_wls)

summary(lm(sqrt(abs(residuals(lmod.T))) ~ fitted(lmod.T)))
```

