---
title: "ReportLoading"
author: "Ian Jiang"
date: "November 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Loading Script}
install.packages("faraway")
install.packages("leaps")
install.packages("Amelia")
install.packages("pls")
#install.packages("MASS")
library(MASS)
#install.packages("faraway")
library(faraway)
#install.packages("nlme")
library(nlme)
library(leaps)
library(Amelia)
library(pls)


#Loading data
data_raw <- read.csv("data_nomiss_specificAQI_updatedNov25.csv")
#Dropping missing values in response
data_raw <- data_raw[!is.na(data_raw$AQI),]
#Assigning date from year, month, day
data_raw$date <- as.numeric( difftime(ISOdate(data_raw$Year, data_raw$Month, data_raw$Day, 0), ISOdate(2016,1,1,0), units="days"))

#TEMPERATURE DATA
plot(data_raw$Temperature, data_raw$Month)
data_raw[data_raw$Temperature < -30,]

# remove iberville, louisiana since it is unlikely a county in LA actually saw 
#temperatures in the -38 range
remove <- c("iberville")
data1 <- data_raw
data1 <- data1[!(data1$County %in% remove),]

plot(data1$Temperature, data1$Month)
data1[which(data1$Temperature < -15 & data1$Temperature > -20 & data1$Month == 4),]


# remove effingham, illinois, greenup, kentucky, and roane, tennessee since 
#they have the exact same value for every day and is unlikely to have -17.78 
#in the middle of the summer
remove2 <- c("effingham", "greenup")
data2 <- data1[!(data1$County %in% remove2),]

data2[which(data2$Temperature < -15 & data2$Temperature > -20 & data2$Month == 7),]

remove3 <- c("roane")
data3 <- data2[!(data2$County %in% remove3),]

plot(data3$Temperature, data3$Month)

qqnorm(data3$Temperature)
qqline(data3$Temperature)
#probably needs transformation


#AQI_PM2.5
summary(data_raw$AQI_PM2.5)
plot(data_raw$AQI_PM2.5)
#all values within 0-500 range

qqnorm(data_raw$AQI_PM2.5)
qqline(data_raw$AQI_PM2.5)
#probably needs transformation


#AQI_PM10
summary(data_raw$AQI_PM10)
plot(data_raw$AQI_PM10, data_raw$Month)
#not all values within 0-500 range

#remove values which are outside of the AQI range of 0-500 since 
#something is not right with those values
data_raw[which(data_raw$AQI_PM10 > 500),]
remove4 <- c(8912, 13425)
data4 <- data3[-remove4,]
data4[which(data4$AQI_PM10 > 500),]

plot(data4$AQI_PM10, data4$Month)

qqnorm(data4$AQI_PM10)
qqline(data4$AQI_PM10)
#probably needs transformation

#AQI_CO
summary(data_raw$AQI_CO)
plot(data_raw$AQI_CO, data_raw$Month)
#all values within 0-500 range

qqnorm(data_raw$AQI_CO)
qqline(data_raw$AQI_CO)
#probably needs transformation


#AQI_NO2
summary(data_raw$AQI_NO2)
plot(data_raw$AQI_NO2, data_raw$Month)
#all values within 0-500 range

qqnorm(data_raw$AQI_NO2)
qqline(data_raw$AQI_NO2)
#probably needs transformation

#AQI_Ozone
summary(data_raw$AQI_Ozone)
plot(data_raw$AQI_Ozone, data_raw$Month)
#all values within 0-500 range

qqnorm(data_raw$AQI_Ozone)
qqline(data_raw$AQI_Ozone)
#probably needs transformation

#AQI_SO2
summary(data_raw$AQI_SO2)
plot(data_raw$AQI_SO2, data_raw$Month)
#all values within 0-500 range

qqnorm(data_raw$AQI_SO2)
qqline(data_raw$AQI_SO2)

qqnorm(data4$AQI_SO2)
qqline(data4$AQI_SO2)

data4[which(data4$AQI_SO2 == 200),]
#remove hawaii, hawaii since every single recorded day has the same AQI_SO2
remove5 <- c("hawaii")
data5 <- data4[!(data4$County %in% remove5),]

qqnorm(data5$AQI_SO2)
qqline(data5$AQI_SO2)
#probably needs transformation


#TOTAL EMISSIONS
summary(data_raw$Total.Emissions)
plot(data_raw$Total.Emissions, data_raw$Month)

data_raw[which(data_raw$Total.Emissions == max(data_raw$Total.Emissions)),]

#harris county (county which houses Houston) has much more total emissions 
#than the others, but no real reason to believe it's a bad data point

qqnorm(data5$Total.Emissions)
qqline(data5$Total.Emissions)
#probably needs transformation

#TESS FINAL DATA (NOT INCLUDING IAN'S REMOVALS)
data <- data5

lmod <- lm(formula = AQI ~ NF3 + Other.GHG + Total.Emissions + HFC + Other.Fluorane + Biogenic.CO2 + Population + CO2 + PFC + HFE + Stationary.Combustion + pp_consumed_MMBtu + Temperature +  Methane + SF6 + Short.Lived.Compounds + Income +  pp_net_gen_MWh, data = data)

data_PM2.5 <- data[!is.na(data$AQI_PM2.5),]
data_PM10 <- data[!is.na(data$AQI_PM10),]
data_CO <- data[!is.na(data$AQI_CO),]
data_NO2 <- data[!is.na(data$AQI_NO2),]
data_ozone <- data[!is.na(data$AQI_Ozone),]
data_SO2 <- data[!is.na(data$AQI_SO2),]

data_PM2.5 <- subset(data_PM2.5, select=-c(AQI))
colnames(data_PM2.5)[colnames(data_PM2.5)=="AQI_PM2.5"] <- "AQI"

data_PM10 <- subset(data_PM10, select=-c(AQI))
colnames(data_PM10)[colnames(data_PM10)=="AQI_PM10"] <- "AQI"

data_CO <- subset(data_CO, select=-c(AQI))
colnames(data_CO)[colnames(data_CO)=="AQI_CO"] <- "AQI"

data_NO2 <- subset(data_NO2, select=-c(AQI))
colnames(data_NO2)[colnames(data_NO2)=="AQI_NO2"] <- "AQI"

data_ozone <- subset(data_ozone, select=-c(AQI))
colnames(data_ozone)[colnames(data_ozone)=="AQI_Ozone"] <- "AQI"

data_SO2 <- subset(data_SO2, select=-c(AQI))
colnames(data_SO2)[colnames(data_SO2)=="AQI_SO2"] <- "AQI"

```